import "./globals.css";

export const metadata = {
  title: "Employee Management System",
  description: "Generated by create next app",
};

// localStorage.clear(); //Clear the Local Storage
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}