import Providers from "@/Components/Providers";
import "./globals.css";

export const metadata = {
  title: "Employee Management System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}